[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  VITE_API_BASE_URL = "https://eventmasterdemo.onrender.com/api/"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200